### ISSUE TITLE
example project

### ISSUE THREAD

**Issue by glenfordwilliams** [wav/grpc-web-dart#1]
is there an example of how to setup using a new project?

**Comment by wav** [comment]
Presently the tests are the example. To add it to an existing project, in your `pubspec.yaml` you would add.

```yaml
grpc_web:
  git: https://github.com/wav/grpc-web-dart
```

You will then be able to import the channel to be consumed in your grpc client as seen in the tests.

```dart
import 'package:grpc_web/grpc_web.dart';
new WebClientChannel(...);
final client = new BookServiceClient(channel);
```

At this time, this works over HTTP 1.1 with a flutter app, but not in the browser.

The example server shows how a `golang` grpc web server is used. It's ripped from straight from [improbable-eng/grpc-web](https://github.com/improbable-eng/grpc-web) examples with a few minor changes.

**Comment by gedw99** [comment]
Maybe have 2 endpoints on the server.
1. Is for pure GRPC and the Flutter clients
2. Is for Web browsers and so have the websocket style.

hen front it with Caddy proxy.

what do you think ?

**Comment by wav** [comment]
> 1. Is for pure GRPC and the Flutter clients
> 2. Is for Web browsers and so have the websocket style.

This project implements a client for the `gRPC-Web` protocol only. My understanding is that the protocol has no reference to *websockets*. It's a "plain way" of constructing a regular HTTP POST request.

This method will be identical (or almost) for both in the browser an out (flutter, cli, ...). The only difference in the implementation is the API that your browser provides (eg. XHR/fetch) to set the headers and body in a request and read the headers and body in a response.

> Then front it with Caddy proxy.

If you have a sample caddy configuration, it can be added to the README. But it's not something I can test. 

You're welcome to fork this to add a endpoint to the `exampleserver.go` to support both `gRPC` and `gRPC-Web`. The server is as it is because it doesn't elaborate examples except for printing for debugging.

**Comment by gedw99** [comment]
then how will you do streaming ? Its going to be either polling or web sockets right ?

**Comment by wav** [comment]
The `gRPC-Web` protocol doesn't define streaming beyond a "server response" stream.

"Server response" stream "parsing" works as it is now as demonstrated in the test. But! It's not really a stream because it waits for the whole response body to be received, hence the TODO.

Full bi-directional streaming will remain a TODO until defined in the `gRPC-Web` protocol.

An ad-hoc/undefined approach is required at this stage to achieve streaming bi-directional from my understanding. But that means it won't work with existing server implementations.

**Comment by gedw99** [comment]
Thanks for the explanation.

I am using the grpc-web from improbable and gophers to build the browser
grpc:

https://github.com/johanbrandhorst/grpcweb-example

Have not had time to try the WASM version yet:

https://github.com/johanbrandhorst/grpc-wasm

**Comment by gedw99** [comment]
@wav Ah thanks for letting me know. 
Ah yes i see it here: https://github.com/wav/grpc-web-dart/blob/master/lib/src/call.dart#L63

I now realise that your only trying to build your Client with Dart ( i guess Dart Web and Flutter, and  so presumably client code using golang / gopherjs / WASM is useless to you ?

SO with your call.dart POST approach, in order for the Client to get a message "pushed" by the server, the client must poll ?

**Comment by wav** [comment]
Pulling in a different ecosystem to dart for a dart project is undesirable.

I've added another issue to address the work done to get streaming working here #2.

**Comment by gedw99** [comment]
Ok so it's long polling pattern.
It's good enough but connection re- establishing from the client will be important I suspect. Might want to check it.
