### ISSUE TITLE
Flutter Web

### ISSUE THREAD

**Issue by joeblew99** [wav/grpc-web-dart#4]
Can this work with Flutter Web ?

**Comment by wav** [comment]
This library uses the `HttpClient` in `dart:io` which is implemented in normal flutter and non-web projects.

`HttpClient` in `flutter_web` doesn't have an implementation as of today (it's empty! unless I'm wrong). That said *some* of `HttpClient` I **guess** cannot be implemented in web because the browser is in-charge of the client. Because the browser is in charge, you must use `XHRHttpRequest` or the `fetch` apis. This is possible to do but hasn't been done yet.

If you don't need `HTTP/1.1` and can use `HTTP/2` then [grpc-web#109](https://github.com/grpc/grpc-dart/pull/109) should do what you want.

**Comment by joeblew99** [comment]
thanks @wav !!
So this example ? https://github.com/grpc/grpc-dart/tree/master/example/grpc-web/web

**Comment by wav** [comment]
Yep. Thats the one... just make sure the server serves gRPC-Web and you
have a cert that your browser accepts.
